name: Receive Repository Dispatch

on:
  repository_dispatch:
    types:
      - my-custom-event

jobs:
  receive_dispatch:
    runs-on: ubuntu-latest
    steps:
     - name: git clone
       run: |
          git config --global user.email "syedimran@4blabs.com"
          git config --global user.name "syedimranFB"
          git clone https://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@github.com/syedimranFB/multi-stage-sender.git
          git clone https://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@github.com/syedimranFB/multi-stage-test.git

          ls && pwd
          
          cp /home/runner/work/multi-stage-test/multi-stage-test/multi-stage-sender/DEMO.txt /home/runner/work/multi-stage-test/multi-stage-test/multi-stage-test
          cd /home/runner/work/multi-stage-test/multi-stage-test/multi-stage-test
          git add .
          git commit -m "testing"
          git push -f --set-upstream https://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@github.com/syedimranFB/multi-stage-test.git main